language: php

php:
  - 5.6
  - 7.0

services:
  - mongodb
  - memcached

env:
  - PHALCON_VERSION="v3.0.0" CC="ccache gcc" PATH="$PATH:~/bin"

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS vegas_test;" -uroot
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-org-server

before_script:
  - phpenv config-add travis/php.ini
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - (cd cphalcon/build; bash install &>/dev/null)
  - phpenv config-add cphalcon/tests/_ci/phalcon.ini &> /dev/null
  - php --ri phalcon
  - travis_retry composer install --dev --no-interaction

script:
  - cp tests/config.sample.php tests/config.php
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - coveralls